[MZL-박현우] feature/modeling
wecode-bootcamp-korea/25-2nd-MZL-backend pull request #1
Opened 2021-10-19 10:18 UTC by Pagnim

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 받은 모델링 수정으로 기반으로 models.py 작성
- 로그인/ 항공예약페이지/ 결제페이지/ 메인페이지

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.App추가
2.Model작성
3.urls.py 추가 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 배웠던 git rebase를 기반으로 commit을 정리후 push 순서를 익혀 진행한점

2021-10-19 15:30 UTC, kyeongraekim requested changes
아래 내용 참고하고 수정해주세요~

2021-10-19 15:30 UTC, kyeongraekim commented on payments/models.py
> +#         db_table = "payments"
해당 부분 파일이 모두 주석 처리되어있네요. 확인 부탁드립니다~

2021-10-19 15:30 UTC, kyeongraekim commented on reservations/models.py
> +    customs_dusty  = models.DecimalField(max_digits=10, decimal_places=2, default=8000)
혹시 변수명의 dusty는 duty를 의도하신 걸까요?

2021-10-19 15:30 UTC, kyeongraekim commented on reservations/models.py
> +class Airportschedule(models.Model):
공항자체에 대한 스케줄 지정을 어떤 의도에서 넣어주신 건가요? 혹시 어떤의도로 작성하신 것 인지 댓글로 설명 부탁드려요~

2021-10-19 15:30 UTC, kyeongraekim commented on reservations/models.py
> +    airlinelogo_image = models.CharField(max_length=2000)
airline의 클래스명에서 이미 자명하고 있으니 변수명의 airline은 지워주시는게 더 좋아보입니다~ 
logo_image 정도가 좋겠네요.

2021-10-19 15:30 UTC, kyeongraekim commented on reservations/models.py
> +    airline          = models.ForeignKey(Airline, on_delete=models.CASCADE)
헤당 내용은 물고 있는 참조 대상이 사라지면 그와 동시에 해당 객체도 사라짐을 의미합니다. 
on_delete 에서 선택할 수 있는 다양한 옵션을 장고 공식문서에서 확인해보세요!~

2021-10-19 15:30 UTC, kyeongraekim commented on payments/models.py
> +#     passenger   = models.ForeignKey(Passenger, on_delete=models.CASCADE)
결제 자체는 사용자가 할 것 이기 때문에 결제 테이블에서의 passenger 선언은 불필요해 보이네요~
대신 reservation에 passenger를 외래키로 무는 것이 필요해 보입니다~

2021-10-20 01:13 UTC, kimfa123 commented on reservations/models.py
> +class Airportschedule(models.Model):
제주 갈때 지역으로 표현 했었는데 모델링 리뷰 할때 지역보다 그 공항 스케줄로 표현 하면 좋을거 같다고 하셔서 공항스케줄로 변경하였습니다

2021-10-20 01:14 UTC, kimfa123 commented on payments/models.py
> +#         db_table = "payments"
확인했습니다 수정하겠습니다 !!

2021-10-20 01:14 UTC, kimfa123 commented on reservations/models.py
> +    customs_dusty  = models.DecimalField(max_digits=10, decimal_places=2, default=8000)
넵 duty 오타가 난거 같습니다 수정하겠습니다!!

2021-10-20 01:14 UTC, kimfa123 commented on reservations/models.py
> +    airlinelogo_image = models.CharField(max_length=2000)
넵 확인했습니다 수정하겠습니다!!

2021-10-20 01:14 UTC, kimfa123 commented on reservations/models.py
> +    airline          = models.ForeignKey(Airline, on_delete=models.CASCADE)
넵 문서 확인해보고 수정하겠습니다!!

2021-10-20 01:17 UTC, kyeongraekim commented on reservations/models.py
> +class Airportschedule(models.Model):
그렇다면 schedule 이란 용어를 빼주셔도 될 것 같네요. Airport 공항에 대한 테이블 (제주, 서울)을 넣는 것이지 공항의 스케줄 자체를 다루는 테이블은 아닐 것 같아서요~

2021-10-20 01:18 UTC, kimfa123 commented on payments/models.py
> +#     passenger   = models.ForeignKey(Passenger, on_delete=models.CASCADE)
![image](https://user-images.githubusercontent.com/89339349/138011933-7c4a7ce2-a8ee-4122-80f5-a4d46ffc83e4.png)

예약자와 탑승자가 다를수 있어서 기입 하여서 필요하다고 보이는데 수정해야 할까요??

2021-10-20 01:25 UTC, kimfa123 commented on reservations/models.py
> +class Airportschedule(models.Model):
아 넵 알겠습니다 !! 수정하겠습니다 !!

2021-10-20 07:08 UTC, kyeongraekim approved these changes

2021-10-20 07:09 UTC, kyeongraekim commented
LGTM!~

2021-10-20 07:11 UTC, merged