ADD:users.view.py file
wecode-bootcamp-korea/25-2nd-MZL-backend pull request #3
Opened 2021-10-20 11:40 UTC by Pagnim

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- utils 데코레이션 파일 카카오 소셜 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. decorator를 위한 utils.py생성
2. 카카오 소셜 로그인 기능 구현
3. 데이터베이스에 담기는 값 확인 완료
4. 이메일과 프로필 사진은 필수 동의가 아닌 선택 동의므로 .get()을 이용하여 구현

2021-10-21 01:17 UTC, kyeongraekim requested changes
프론트랑 혹은 PostMan을 사용해서 카카오로 부터 잘 정보를 받았음을 의미하는 성공메세지 스샷으로 찍어서 업로드 해주세요!~

2021-10-21 01:17 UTC, kyeongraekim commented on users/models.py
> +    profile_image = models.CharField(max_length=500)
모델 PR도 따로 올라와 있는 것으로 아는데 이곳 에는 user view에 관련한 내용만 푸시해주세요~

2021-10-21 01:53 UTC, Pagnim commented on users/models.py
> +    profile_image = models.CharField(max_length=500)
네 수정하였습니다!

2021-10-21 06:53 UTC, kyeongraekim requested changes
해당 view 파일의 유닛 테스트를 작성해주시고 같이 푸시 해주세요~

2021-10-24 05:25 UTC, kyeongraekim requested changes
아래 내용 확인하고 수정해주세요!~

2021-10-24 05:25 UTC, kyeongraekim commented on users/tests.py
> +    def test_kakao_social_login_fail(self, mocked_request):
카카오 로그인이 실패한 경우가 여러가지가 될 것 같네요. 각각 의도한 에러 핸들링이 잘 이루어 지는지 파악하기 위해 소셜 로그인 시 발생할 수 있는 여러 에러들과 직접 except 문으로 처리한 다양한 에러들이 잘 작동하는지 다루어 주세요!~

2021-10-25 04:01 UTC, Pangim commented on users/tests.py
> +    def test_kakao_social_login_fail(self, mocked_request):
추가했습니다!

2021-10-25 15:26 UTC, kyeongraekim requested changes
현우님 추가 수정 사항 반영해주세요!~

2021-10-25 15:26 UTC, kyeongraekim commented on users/tests.py
> +    def test_kakao_social_not_do_not_exist_login_fail(self, mocked_request):
test_fail_xxxx의 형식으로 test의 성공/실패 유무를 더 쉽게 알아볼수 있게/가독성 향상을 위해 함수명 배치를 바꾸어주세요!~ 그리고 test_kakao_social_not_do_not 의 표현이 이중 부정이라 모호하게 보이네요!~

2021-10-25 15:26 UTC, kyeongraekim commented on users/views.py
> +            headers      = {'Authorization': f"Bearer {access_token}",}
access_token 뒤에 불필요해 보이는 쉼표가 보이네요~ 의도하신 내용인지 확인 부탁드려요~

2021-10-26 01:23 UTC, Pangim commented on users/tests.py
> +    def test_kakao_social_not_do_not_exist_login_fail(self, mocked_request):
수정했습니다

2021-10-26 01:23 UTC, Pangim commented on users/views.py
> +            headers      = {'Authorization': f"Bearer {access_token}",}
수정하였습니다!

2021-10-26 05:33 UTC, kyeongraekim requested changes
아래 내용 참고해서 추가 수정 해주세요!~

2021-10-26 05:33 UTC, kyeongraekim commented on users/tests.py
> +                    "msg":"NotRegisteredUserException"
컨벤션 정렬을 잘 맞추어주세요!~

2021-10-26 05:33 UTC, kyeongraekim commented on users/tests.py
> +        header             = {'HTTP_Authorization' : 'token3'}
혹시 token 뒤에 숫자 2와 3은 왜 붙을까요? 댓글로 설명해주세요!~

2021-10-26 05:33 UTC, kyeongraekim commented on users/tests.py
> +    def test_fail_kakao_social_login(self, mocked_request):
함수명에는 social login 이 Fail 되었다라는 결과적의미 보다 어떠한 상황을 의도했고 실제로 fail이 났는지 의미를 표현해주는것이 중요합니다. 개발자들에게 함수명, 변수명 네이밍은 정말 중요하니까 보다 신경써 주세요!~

2021-10-26 05:33 UTC, kyeongraekim commented on users/views.py
> +                    profile_image = user_info["properties"].get("profile_image")
위쪽과 달리 이 두곳에서는 왜 get 메소드를 쓰셨을까요? 댓글로 알려주세요!~

2021-10-26 06:23 UTC, Pangim commented on users/tests.py
> +        header             = {'HTTP_Authorization' : 'token3'}
위쪽 테스트와 구분지으려고 표시했는데 삭제하였습니다

2021-10-26 06:24 UTC, Pangim commented on users/tests.py
> +                    "msg":"NotRegisteredUserException"
수정하였습니다

2021-10-26 06:24 UTC, Pangim commented on users/views.py
> +                    profile_image = user_info["properties"].get("profile_image")
이메일과 프로필 이미지는 필수동의가 아닌 선택동의 항목이라 유저가 동의를 하지 않을 경우 오류가 났기 때문에 get을 사용하였습니다

2021-10-26 06:31 UTC, Pangim commented on users/tests.py
> +    def test_fail_kakao_social_login(self, mocked_request):
수정하였습니다

2021-10-27 08:10 UTC, kyeongraekim approved these changes
LGTM!~

2021-10-27 08:11 UTC, merged