[MZL-김지훈:MODIFY]feature/models.py_views.py-modify
wecode-bootcamp-korea/25-2nd-MZL-backend pull request #5
Opened 2021-10-25 04:08 UTC by kimfa123

- [ ] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
좀더 편하다고 생각한 reservations 로직으로 다시 기능 구현 해보았습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로직 구현시 좀더 간편한게 코드를 작성해 보았습니다. 

2 airline과 seat class 정리
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- django.db.models 로 q를 사용해 보았습니다. 관리하기 위해서는 네이밍 정리가 중요하단걸 알았습니다. 

<br />

## :: 기타 질문 및 특이 사항

2021-10-25 15:35 UTC, kyeongraekim requested changes
지훈님 아래 내용 참고하셔서 수정해주세요!~

2021-10-25 15:35 UTC, kyeongraekim commented on my_settiong.py
> +ALGORITHM = 'HS256'
my_settings.py 가 올라와버렸네요! 큰 사고입니다 ㅎㅎ 깃이그노어 추가, 깃 캐쉬삭제후 재 푸시해주세요!

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/models.py
> +    flightid       = models.CharField(max_length=45)
pk 값과 혼동을 유발할 수 있는 id말고 다른 변수명이 없을까요?

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/models.py
> +        db_table = 'flights'
Reservation 모델클래스에 table명은 flights라고 지어주시는게 많은 혼선을 자아낼 것 같네요. 수정 부탁드려요!~

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/models.py
> +    reservation_id = models.ForeignKey(Reservation, on_delete=models.SET_NULL, null=True)
외래키 로 걸게되면 ORM에서 '_id' 를 자동으로 붙여줍니다. reservation 으로 지워야 의도한 내용이 구현되실 거에요!~

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/tests.py
> +import unittest
models.py 내용이 있다가 갑자기 test.py 가 보이네요? 기능과 성격에 맞는 파일들끼리만 올려주시고 그 외에는 새로운 브랜치를 파주셔야합니다!~

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/tests.py
> +    maxDiff = None
현재 올려주신 PR내 어디에도 쓰이지 않는 변수를 선언해주신것 같아 보이네요. 확인 부탁드려요!~

2021-10-25 15:35 UTC, kyeongraekim commented on reservations/views.py
> +        seat_class          = request.GET.getlist('seat_class', None)   #좌석 등급 필터 리스트
뒤에 별도 설명을 위한 한글 주석들 불필요한 내용입니다/ 삭제 해주세요!~

2021-10-26 01:05 UTC, kimfa123 commented
넵 경래님 감사합니다 수정후 다시 올리겠습니다 !!

2021-10-26 01:46 UTC, kyeongraekim requested changes
안녕하세요 지훈님!~  리베이스 부탁드릴게요!~

2021-10-26 06:27 UTC, kimfa123 commented
경래님 리베이스 해서 올렸습니다

2021-10-26 06:58 UTC, kyeongraekim requested changes
아래내용 참고해서 수정해주세요!~

2021-10-26 06:58 UTC, kyeongraekim commented on reservations/views.py
> +        low_price = sorted(reservation_list, key=lambda k: k['basic_price'])
정렬을 위해 람다를 써주신 것 같은데 장고의 order_by 기능을 사용 안한 이유가 있을까요?

2021-10-26 06:58 UTC, kyeongraekim commented on reservations/views.py
> +        ticketing_fee  = 0
해당 수치가 view 파일 상에서 하드코딩 되어 있는 것 처럼 보이네요? 
db에 반영되어있는 수치면 최대한 db에서 끌어다 써주시고, 
view 파일에서 다루고 싶으시다면 상수처리를 위에 따로 변수선언해서 관리에 용이하게 바꿔주세요!

2021-10-26 06:58 UTC, kyeongraekim commented on reservations/views.py
> +            "depart_weekday"     : FlightWeekday.objects.filter(date = flight_condition['depart_date'], reservation_id = reservation.id)[0].weekday,
전에 수정해주신 것처럼 [0] 인덱싱보다 first()를 사용 해주세요!~ 추후 에러 핸들링시 더 효율적인 방법입니다~

2021-10-26 09:02 UTC, closed without merging