[MZL-박현우: ADD]menus_view_test
wecode-bootcamp-korea/25-2nd-MZL-backend pull request #9
Opened 2021-10-26 12:43 UTC by Pangim

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- menu 뷰 출력

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메뉴와 서브프로덕트를 get했을 시 프론트와 맞춘 데이터 형식으로 리턴해주었다.
2. 유닛테스트를 진행하였다.

<br />

![image](https://user-images.githubusercontent.com/75020336/138880804-8bf90364-f646-4569-b99b-3df56feb7841.png)
유닛테스트

2021-10-27 01:56 UTC, kyeongraekim requested changes
현우님 아래 내용 확인하고 수정 반영해주세요!~

2021-10-27 01:56 UTC, kyeongraekim commented on menus/tests.py
> +class Test(TestCase):
실제 테스트와 유사한 환경을 위해 단 하나의 데이터만 넣는 것 보다 여러개 최소(3-4개)를 넣고 아래에서도 테스트해보세요!
그리고 assertEquals에 성공할 떄 반환하는 리턴메세지 값도 비교할 수 있게 해주세요!~

2021-10-27 01:56 UTC, kyeongraekim commented on menus/views.py
> +            elif response == "별":
이곳에 공백 라인 하나가 있어야 할 것 같네요!~

2021-10-27 01:56 UTC, kyeongraekim commented on menus/views.py
> +                            Rate_id = data["id2"]
id 1/2 로 받는 내용 키값이 다소 불분명해 보이네요!~ 이 코드를 처음 보는 사람들도 이해가 가기 쉬운 키값명으로 변경 해보시는게 어떨까요?

2021-10-27 01:56 UTC, kyeongraekim commented on menus/views.py
> +        count = SubProduct.objects.all().annotate(sum_count=Count('productstar__Rate'))
annotate 테이블 두개를 따로따로 만들어주셨는데 이렇다면 불필요한 연산이 수반됩니다. 이 두개를 합칠 수 있습니다!~  
1) annotate 테이블 두개를 한 변수명에서 선언하는 법과   
2) 해당 메소드 내에서 distinct=True를 선언하는 법을 리서치해서 적용해보세요!~

2021-10-27 02:07 UTC, Pangim commented on menus/views.py
> +            elif response == "별":
수정하였습니다

2021-10-27 02:07 UTC, Pangim commented on menus/views.py
> +                            Rate_id = data["id2"]
수정하였습니다!

2021-10-27 02:24 UTC, Pangim commented on menus/views.py
> +        count = SubProduct.objects.all().annotate(sum_count=Count('productstar__Rate'))
수정하였씁니다.!

2021-10-28 03:31 UTC, Pangim commented on menus/tests.py
> +class Test(TestCase):
수정했습니다.. 머지부탁드려요 ㅠㅠ

2021-10-28 07:34 UTC, kyeongraekim approved these changes
LGTM!~

2021-10-28 07:34 UTC, kyeongraekim commented on menus/tests.py
> +
불필요한 공백 한칸 지워주세요!~

2021-10-28 07:34 UTC, merged